# Site settings
title: Arshita Sandhiparthi # site title
description: >- # site description
  My name is Arshita and I am a political science and computer science student at the University of the Pacific.
lang: en-US # default lang
timezone: America/Los_Angeles # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Arshita Sandhiparthi # author name
  bio: >- # tell to the world
    My name is Arshita and I am a political science and computer science student at the University of the Pacific.
  username: arshita237 # general username
  github: arshita237 # github username
  twitter: twitter_username # twitter username
  facebook: facebook_username # facebook username
  email: arshita.237@email.com # email address
  avatar: /assets/img/avatar.jpg # Avatar

# URL settings
url:  #
baseurl: /arshita237.github.io
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
